version: '3'
services:
  cocpp:
    container_name: cocpp-dev
    build:
      context: .
      dockerfile: dockerfile
      args: 
        USERNAME: ${USERNAME}
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        GROUPNAME: ${GROUPNAME}
        HOME: ${HOME}
        GITNAME: skyfire
        GITEMAIL: skyfireitdiy@hotmail.com
    volumes: 
      - $PWD/..:/code/cocpp
      - $HOME/.ssh:${HOME}/.ssh
    working_dir: /code/cocpp
    entrypoint:
      - bash
      - "-c"
      - "while true; do sleep 1; done"